Mirror ticks #30
lemeryfertitta/Climbdex pull request #34
Opened 2024-02-08 05:28 UTC by abant07

This feature here basically looks at all the climbs a user has done and sees if they completed it. If they complete the climb, it gets checked off. If they complete the climb in reverse, then then a reversed checkmark shows. However, if a user marks the climbs in the forward and reverse way, then a forward and reflected check mark shows.

2024-02-08 18:23 UTC, lemeryfertitta requested changes
Thanks for the PR! Great job - I was able to take a look locally and it was looking pretty good. I think there are a few necessary changes before we merge this, but this is a great start.

2024-02-08 18:23 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +  const iconSvg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
This appears to be more or less a copy-paste of the code in `drawResultsPage`. To avoid this large repetition, we could create the HTML element in `drawResultsPage` and pass the element to `drawClimb`.

I would recommend just replacing "difficultyAngleText" with "difficultyAngleElement" which contains all of the HTML necessary to render the difficutly, angle, and tick SVG.

2024-02-08 18:23 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +    }
This large block should be refactored to a helper function, e.g. `getTickSvg()`

2024-02-08 18:23 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +      );
Rather than hardcoding the mirrored SVG path, it would be better for maintainability to use the [transform](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform) attribute. In this way, we could swap out the base SVG or alter the mirrored image much more easily.

2024-02-08 18:23 UTC, lemeryfertitta commented on climbdex/views.py
> +    ticked_and_mirror_climbs = get_mirror_and_ticked_climbs(board_name, login_cookie) if login_cookie else []
This makes two additional API calls which is unnecessary and potentially quite costly to performance. Instead of creating three objects, let's just augment `ticked_climbs` to include the `is_mirror` attribute. We will need to change the data type of `ticked_climbs`, but that is fine. I would recommend a dictionary of the following scheme:

```python
{
    "<uuid>": 
    {
        "<angle>": "<tickType>"
    }
}
```

e.g.


```python
{
    "2c15ec2307e32d0d82b73f2865a2eec9":
     {
        40: 0,
        30: 1,
        20: 2
    }
}
```

With 0=normal tick, 1=mirror tick, and 2=normal and mirror tick. Other similar data structures could work. The main idea is to not make additional API calls or create more objects than necessary.

2024-02-08 18:23 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +    iconSvg.setAttribute('width', '20px');
In my opinion 16x16 looks a little better. 20x20 seems a bit too large.

2024-02-08 18:23 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +      nameText.appendChild(iconSvg);
This makes the SVG too close to the text. There needs to be some space in between the text and tick icon. This could probably just be done with just a space at the end of the `difficultyAngleText`.

2024-02-08 18:23 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +  anchor.appendChild(iconSvg)
I liked the tick where it was before, which was immediately after the difficultyAngleText, not on the climb name anchor.

2024-02-08 19:19 UTC, abant07 commented on climbdex/static/js/results.js
> +  const iconSvg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
Ok I think that makes sense, because I do pass in the same element, so I will try that out and get back to you. It might take me a day or two to take a look at everything and fix it efficiently, because I have fallen a little busy with school. But I will keep you updated.

Thanks

2024-02-10 19:43 UTC, abant07 commented
Ok I believe I fixed everything, let me know if any problems occur

2024-02-11 16:22 UTC, lemeryfertitta requested changes
Thanks for the updates! This is looking closer, but when I tested it it seems like the doubled checks for both ticks are not working anymore, and there are a few code cleanup issues as well.

I appreciate the time you've spent on this. I'm happy to help finish it up if you are busy, but I also wanted to give you feedback and the chance to finish it on your own if you prefer.

2024-02-11 16:22 UTC, lemeryfertitta commented on climbdex/views.py
> +                climbs[f'{log["climb_uuid"]}-{log["angle"]}'] = 1 #1 is normal tick
I'm having a hard time following what you are looking to do here. Also looping three times in a row over the same object is inefficient and more complex than needed. I suspect there is a bug in this logic because I'm no longer seeing the doubled ticks (although I haven't investigated closely, could also be in the SVG logic).

Here is a nice simple implementation of this algorithm:

```suggestion
    ticked_climbs = {}
    normal_tick = 0
    mirror_tick = 1
    both_tick = 2
    for log in logbook:
        key = f'{log["climb_uuid"]}-{log["angle"]}'
        tick_type = mirror_tick if log["is_mirror"] else normal_tick
        existing_tick = ticked_climbs.get(key)
        ticked_climbs[key] = both_tick if existing_tick is not None and existing_tick != tick_type else tick_type
```

2024-02-11 16:22 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +  const iconPath2 = document.createElementNS(
This doesn't need to be created unless tickedClimbs == 2 (mirror_tick), so we should just create it there. Also, I highly recommend more descriptive names. `mirroredCheckPath` is a nice name for this variable.

2024-02-11 16:22 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +  let centerX = 1920 / 2;
Worth defining a constant `const viewboxSize = 1920` to help explain this. Also please use `const` for constant variables.

2024-02-11 16:22 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +  if (tickedClimbs[`${uuid}-${angle}`] == 2) {
Worth defining 0,1,2 as constants like `NORMAL_TICK, MIRROR_TICK, BOTH_TICK`

2024-02-11 16:22 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +function getTickSvg(node, uuid, angle) {
this should only get called if we have a tick IMO, I don't think it should be checking both for the tick _and_ drawing it, the function is doing too much. Let's just have this return an SVG and take tick_type as the only input. We can check for ticked outisde of this function.

2024-02-11 16:22 UTC, lemeryfertitta commented on climbdex/templates/results.html.j2
> +      const tickedClimbs = {{ ticked_climbs }};
this should be `ticked_climbs | tojson` i think, I think its only happening to work right now because the string representation of a dictionary _sometimes_ is valid JSON but it is not guaranteed.

2024-02-11 18:26 UTC, abant07 commented
It's alright, I was able to fix it. Let me know if I missed something, I am fine with going back and fixing

2024-02-12 18:35 UTC, lemeryfertitta approved these changes
Thanks for all of the updates. I made some tweaks as one of my comments hadn't been addressed and there was a merge conflict. Will merge this one in and deploy it now.

2024-02-12 18:35 UTC, merged