62 toast message on error
lemeryfertitta/Climbdex pull request #65
Opened 2024-05-03 19:28 UTC by brmnjsh

- added validations with https://github.com/Ge0rg3/flask-parameter-validation
-  utilized bootstraps toasts. for error notifications
-  some small functional changes

2024-05-03 19:55 UTC, brmnjsh commented on climbdex/static/js/results.js
> +backAnchor.href = location.origin + "/filter" + location.search;
the `?` is already a part of `location.search`

2024-05-03 21:13 UTC, lemeryfertitta requested changes
Really cool, thanks for the contribution! Just two small suggestions, one about the UI and one about the code.

2024-05-03 21:13 UTC, lemeryfertitta commented on climbdex/api.py
> +        return error_handler(e)
Could we use [registered error handlers](https://flask.palletsprojects.com/en/2.3.x/errorhandling/) for the API blueprint? I think that it would make this a bit cleaner.

2024-05-03 21:13 UTC, lemeryfertitta commented on climbdex/templates/climbCreation.html.j2
> +    {% include 'toast.html.j2' %}
I'd like to increase the delay or potentially never automatically hide the toast notification if possible.

Also, it would be great to move it somewhere more central, I felt like I had to look for it a bit. Maybe just under the "heading" template, centered.

2024-05-03 21:34 UTC, brmnjsh commented on climbdex/api.py
> +        return error_handler(e)
ok sure!

2024-05-03 21:35 UTC, brmnjsh commented on climbdex/templates/climbCreation.html.j2
> +    {% include 'toast.html.j2' %}
alright, I'll change to only manual dismissal, as well as making sure it appears in a more central location!

2024-05-05 02:13 UTC, brmnjsh commented on climbdex/static/js/results.js
> +backAnchor.href = location.origin + "/filter";
no need to add the query params here as they are both incorrect, and not needed as `history.back()` preserves the original parameters.

2024-05-05 03:10 UTC, brmnjsh commented on climbdex/api.py
> +def parameter_error(e):
@lemeryfertitta, I'm not sure if we still want to keep this parameter level error handler.... I do like validations however...

2024-05-06 14:52 UTC, brmnjsh commented on climbdex/api.py
> +@blueprint.errorhandler(Exception)
@lemeryfertitta do we want to handle all `Exceptions` like this, or should we do something different for certain exceptions (4xx vs 5xx level errors, etc)?

2024-05-06 21:19 UTC, lemeryfertitta requested changes
Thanks for the updates - just one comment to resolve and then I'll merge this in and get both of your PRs deployed!

2024-05-06 21:19 UTC, lemeryfertitta commented on climbdex/api.py
> +@blueprint.errorhandler(Exception)
All exceptions are fine for now, don't see any reason to distinguish them at this point

2024-05-06 21:19 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +backAnchor.href = location.origin + "/filter";
The point of this is to be able to share search results and then when someone follows the shared link, the "back" link takes them to a filter for the same board. For example, if you follow [this link](https://climbdex.com/results?minGrade=17&maxGrade=26&name=&angle=30&minAscents=100&sortBy=ascents&sortOrder=desc&minRating=1.0&onlyClassics=0&gradeAccuracy=1&settername=&holds=&mirroredHolds=&board=kilter&layout=1&size=8&set=1&set=20&roleMatch=strict) and click the back button, you should get to the filter page for Kilter. With your change, I believe you would get https://climbdex.com/filter which is an error page.

You are correct that the parameters are not exactly right - they are a superset and some of them are ignored. Ideally, we'd either prepopulate the inputs with the correct values from the params, or we would trim the params to be only the relevant ones that are evaluated on page load. I'll create a separate issue for this, but please keep the `location.search` addition for now to avoid breaking this functionality.

2024-05-06 21:19 UTC, lemeryfertitta commented on climbdex/api.py
> +def parameter_error(e):
Yeah, I think the validation is nice, fine with keeping it!

2024-05-07 19:24 UTC, brmnjsh commented on climbdex/static/js/results.js
> +backAnchor.href = location.origin + "/filter";
Ah okay, I understand.

I'll add it back, and maybe I'll take a look at [#66](https://github.com/lemeryfertitta/Climbdex/issues/66)

2024-05-07 19:25 UTC, brmnjsh commented
@brmnjsh ok, I added the `location.search` back. Should be g2g now!

2024-05-13 14:26 UTC, lemeryfertitta approved these changes
Thank you!

2024-05-13 14:26 UTC, merged