Add only hands filter
lemeryfertitta/Climbdex pull request #69
Opened 2024-07-21 04:49 UTC by ItsDang

For issue #58. Implemented by adding a not in filter on the holds selected as if they were feet.

2024-07-22 18:03 UTC, lemeryfertitta requested changes
Thanks for the PR! Some updates needed to get this working perfectly but seems like a solid start.

2024-07-22 18:03 UTC, lemeryfertitta commented on climbdex/db.py
> +def get_frames_not_like_feet_clause(holds,foot_placement_role):
This doesn't really work unless there is only one hold selected. For example, if I am using the "Only Hands" filter and I select two holds, I don't want to see climbs where one of them is used as a foot, which is what happens with this filter in the current changes. This only works to filter out climbs where _all_ of the selected holds are feet instead of climbs where _any_ of the selected holds are feet.

We can accomplish this by having a NOT LIKE clause for each possible foot placement instead of one clause with all of them.

2024-07-23 13:00 UTC, ItsDang commented on climbdex/db.py
> +    print(match_roles, filter_feet)
Yep will double check prints before sending another PR!

2024-08-14 21:31 UTC, lemeryfertitta approved these changes
LGTM! Did a little testing and it seems to be working nicely 😄. Thanks for the PR, will get this one deployed shortly.

2024-08-14 21:31 UTC, merged