Tick Climbs and Show Stats
lemeryfertitta/Climbdex pull request #72
Opened 2024-08-12 08:37 UTC by gardaholm

This PR addresses #46, #54, #55
For testing I've put this branch online on fly.to: [climbdex.why.dev](https://climbdex.why.dev)

## Menu Elements and Result View
Dropdown / Hamburger Menu is shown to clean up the Result view a bit. If user is logged in there is an option to logout, tick climb and show stats. If user user is not logged in there is only the beta information available. 
Result List marks Sends in green and Attempts in yellow, to give a quick information about the status of the climb. 

- [ ] To support this view the Boardlib PR https://github.com/lemeryfertitta/BoardLib/pull/41 is needed to fetch and collect the logbook in the correct way. I've currently set my Branch in the requirements.txt for testing. 

<img width="1163" alt="image" src="https://github.com/user-attachments/assets/a82288cf-683b-48ae-8bea-e7ebbb45a871">

## Simple Climbing and Attempt Stats
If the user is logged in, a separate menu item for Statistics is shown. This modal shows amount of attempts and sessions and when the last session was in a very basic form. I guess this place could be used for further improvements like suggested in Issue https://github.com/lemeryfertitta/Climbdex/issues/28 

<img width="1106" alt="image" src="https://github.com/user-attachments/assets/958f7a52-8ce4-481d-ab14-cb096a2493de">

## Tick Modal
Ticking climbs can be done via the new modal, which should be way faster than compared to the aurora app. Ticking a Climb is done via the boardlib function save_ascent. Difficulty is prefilled but can be changed. Number of attempts can be set when the slider is set to Send instead of Flash. 

- [ ] Only Ascents are currently possible, but it should be easy to hook up a save_attempt function and add a 3rd button into the modal (flash / send / attempt) as written here 
- [ ] For the bids and attempts in the api we currently use the same value, because it's unclear what fields are being used. But so far comments, tries, rating, comments, emojis, etc. are all shown correctly in the aurora apps. 

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/f3b7e7b3-070e-4e6f-a3de-8d20f5fe80db">

2024-08-14 22:04 UTC, lemeryfertitta requested changes
Awesome! I played with this briefly but generally seems like a really awesome feature addition. Had some minor comments on the functionality with my quick test drive, but mostly looking good to me. I'll spend a bit more time playing around with it before we get it merged. Just a few comments on code quality items, and obviously we need to get the boardlib updates in first, but would be happy to get this merged and deployed soon!

Thanks @gardaholm!

2024-08-15 16:34 UTC, lemeryfertitta commented on climbdex/api.py
> +            attempt_id=attempt_id,
Just an FYI that this can just be 0, that's what all new ascents are saved as on the apps. It's just a legacy value at this point as far as we can tell.

2024-08-19 11:36 UTC, gardaholm commented on climbdex/static/js/results.js
> +  const gradeMapping = {
changed it to the same way, which is used to get the grades for the filterselection.

2024-08-19 12:00 UTC, gardaholm commented on climbdex/static/js/results.js
> +        " ago.";
get it, for shorter terms I find the other way easier to read, but if ticks are over a year old, it looks a bit strange. changed the days_pass_since_last_try to mm/dd/yyyy

2024-08-19 12:01 UTC, gardaholm commented on climbdex/templates/results.html.j2
> +      const gradeMapping = {
see comment above.

2024-08-19 12:02 UTC, gardaholm commented on climbdex/api.py
> +from flask import Flask, request, jsonify, Blueprint, json
ah true, thats why it didn't work just with the import flask alone. 
reverted back. definitely better this way!

2024-08-20 13:32 UTC, gardaholm commented on climbdex/api.py
> +            attempt_id=attempt_id,
alright, so I guess we can keep it the way it is right now?

2024-08-20 13:35 UTC, gardaholm commented
updated `aggregated_logbook()` to use the `aggregate=True` parameter for the modified logbook_entries as written in this PR https://github.com/lemeryfertitta/BoardLib/pull/41

2024-08-20 16:53 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +      : parseInt(document.getElementById("attempts").value);
Let's use 0 here. This becomes incorrect when attempts are >10, and this is a legacy value anyways.

2024-08-20 16:55 UTC, lemeryfertitta commented on climbdex/api.py
> +            attempt_id=attempt_id,
I think we should set it to 0 to avoid adding incorrect data and match the behavior of the Aurora apps. Made this suggestion where you are setting it

2024-08-22 19:37 UTC, gardaholm commented on climbdex/static/js/results.js
> +      : parseInt(document.getElementById("attempts").value);
are you sure that attempt_id should be 0?
When I use it as it is now I get the correct values when I check the log in the app:
<img width="372" alt="image" src="https://github.com/user-attachments/assets/421fbf8f-1dfc-4a8c-9b7d-c9aebf0ca2e4">

2024-08-23 17:51 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +      : parseInt(document.getElementById("attempts").value);
See discussion here: https://github.com/lemeryfertitta/BoardLib/issues/22#issuecomment-1999204218

Only the bid_count is being used, and the app always sends attempt_id as 0. Since attempt_id is being ignored, we could theoretically send anything, but I would prefer that we mirror the app behavior as closely as possible to avoid future bugs (in Climbdex or the Aurora apps) due to the inconsistency.

2024-08-23 20:22 UTC, gardaholm commented on climbdex/static/js/results.js
> +      : parseInt(document.getElementById("attempts").value);
Ok, thanks for the link. Will test it again. With the code it only showed the tries for me when I sent them as attempt_id, but ignored them when I used bid_count. But just had a quick look on the ride and probably mixed something up ...

2024-08-26 13:05 UTC, gardaholm commented on climbdex/api.py
> +            attempt_id=attempt_id,
attempt_id is now set to 0 and bid_count is used. 
I just had problems generating flashes (with the flash icon in the tension but), but I logged climbs that I've already done and forgot that they can't be flashed anymore … 🙄
so working as expected :)

2024-08-26 13:06 UTC, gardaholm commented on climbdex/static/js/results.js
> +      : parseInt(document.getElementById("attempts").value);
attempt_id is now set to 0 and bid_count is used.
I just had problems generating flashes (with the flash icon in the tension but), but I logged climbs that I've already done and forgot that they can't be flashed anymore … 🙄
so working as expected :)

2024-08-26 18:49 UTC, lemeryfertitta commented on climbdex/static/js/results.js
>    frames,
I tried updating boardlib to 0.7.1 and running this PR locally. There were a number of things that were broken for me:

- Upon successful login there is no indication of success (the login text doesn't change) and climbs don't appear to be ticked.
- Board image is overflowing, at least for Kilter 8x12
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/732e5969-43f3-44af-8588-00c574d7ed94">


Let me know if you are experiencing the same or if I'm doing something wrong!

2024-08-26 19:29 UTC, gardaholm commented on climbdex/static/js/results.js
>    frames,
strange, didn't happen on our tests here, but I will spin up our test version on fly.io with the official boardlib 0.7.1 and will check it. will probably be able to do it tomorrow morning. sorry for that!

2024-08-27 07:51 UTC, gardaholm commented on climbdex/static/js/results.js
>    frames,
are you sure it installed the new requirements?
I've spinned a fly.io version here https://climbdex-wandering-moon-444.fly.dev/  (linked to boardlib 0.7.1)
and it seems to work for me …
- tested kilter + tension board with my aurora credentials
- I could login, and get the different status message (You're logged in!)
- can see my ticked and tried climbs (green + yellow)
- could log my climb (logged climbs only get displayed after a full refresh, when the logbook is renewed), also get the Successfull Tick Message. 
- the problem with the kilter and tension board classic layout can be fixed via css (will add a commit, seems to be a overflow problemon certain screen dimensions)

2024-08-27 17:21 UTC, lemeryfertitta commented on climbdex/static/js/results.js
>    frames,
Ah, I found the issue. The local deployment bind I was running on `0.0.0.0:8000` (was doing it for some mobile testing) didn't allow the cookie to be stored, so it just silently was trying and failing to set the cookie. Created #83 for that, as it's pretty confusing why the login doesn't work if your cookies aren't enabled, but it is unrelated to your PR here. As an aside, I figured out how to close the modal without refreshing the whole page (your `location.reload` change), but I'll just update that in a separate PR.

I think the only thing that is a regression from this PR is the overflow issue, I think its just some issue with the bootstrap containers that were changed to add the new buttons and such.

Also, I just played with the tick feature a little bit more and had a few additional thoughts:

1. Ticking repeats is a little bit weird, it looks identical to trying the climb over multiple sessions and only sending once vs. sending in multiple sessions. I wonder if we shouldn't be trying to aggregate here, and we should just show a list of sessions for each climb. So basically this would just be the list of all of the logbook entries from boardlib for a specific climb

2. Maybe we can rename "Statistics" to "Your Attempts" or something similar. I feel like when you click statistics you expect to get the same information as the info button on the official apps, which shows other peoples ticks and grade distribution chart and such. 

We can leave 1. as is for now and change that in a future PR, I think it's worth just getting the current functionality in. Let's get the overflow issue and rename the menu item for this PR.

2024-08-27 18:03 UTC, gardaholm commented on climbdex/static/js/results.js
>    frames,
> I think the only thing that is a regression from this PR is the overflow issue. I think its just some issue with the bootstrap containers that were changed to add the new buttons and such.
> 
should be fixed. I think the occurence is pretty rare >> probably 13'' notebooks + board images which are very long.

> Also, I just played with the tick feature a little bit more and had a few additional thoughts:
> 
> 1. Ticking repeats is a little bit weird, it looks identical to trying the climb over multiple sessions and only sending once vs. sending in multiple sessions. I wonder if we shouldn't be trying to aggregate here, and we should just show a list of sessions for each climb. So basically this would just be the list of all of the logbook entries from boardlib for a specific climb

true. I was thinking about the same: if you open the log item a small indication about the sessions would be great and if there are already sessions logged then the flash button can be hidden (I already ran into this issue a few times and wondering why the app don't show the flash icon …). Information is already there so I guess it shouldn't be too much work for a future PR. 

What this PR is also missing is a indication that the current climb is logged (besided the success message). It would be nice if the entry in the result list gets the background color and the tick icon after saving the modal. Shouldn't be too hard, maybe I can do this in another PR, it's more a cosmetical thing I guess …

> 2. Maybe we can rename "Statistics" to "Your Attempts" or something similar. I feel like when you click statistics you expect to get the same information as the info button on the official apps, which shows other peoples ticks and grade distribution chart and such.

also fine, renamed the entries (Menu + Modal-Title).
Would love to have the stats. grad distribution and comment also somewhere in climbdex. but probably something for later. 

> We can leave 1. as is for now and change that in a future PR, I think it's worth just getting the current functionality in. Let's get the overflow issue fixed and rename the menu item for this PR.

2024-08-29 21:59 UTC, lemeryfertitta commented on climbdex/static/js/results.js
>    frames,
> should be fixed. I think the occurence is pretty rare >> probably 13'' notebooks + board images which are very long.

Didn't really like the overflow approach so I changed it back to the original behavior to scale based on viewport. Also made a few other minor changes to some of the nomenclature but will get this merged and deployed now! Lots of other improvements to make but its a huge start 😄

2024-08-29 21:59 UTC, lemeryfertitta approved these changes

2024-08-29 22:00 UTC, merged

2024-08-30 05:59 UTC, gardaholm commented
Thanks for the merge and your work! Hope its a good first addition for the save dialog and we could save you at least some time :)
and thanks for refining the code 🙏