Mirror climb
lemeryfertitta/Climbdex pull request #88
Opened 2024-09-02 00:42 UTC by ItsDang

Added mirror climb button to drop down menu. It acts like a toggle. Currently it resets back to not mirrored if you refresh or switch searches.

2024-09-02 07:08 UTC, gardaholm commented
Nice, had a quick play today – logging seems to work fine 👌
Only thing missing is that you can't send the mirrored version to the board via bluetooth. Tried it on the TB2 but I only get the original layout. Would be great to have this addition to.

2024-09-02 18:28 UTC, lemeryfertitta requested changes
Thanks @ItsDang! Tested and looks great to me, nice clean implementation as well. Just one change needed to hide (or disable) the button on non-symmetrical layouts.

2024-09-02 18:28 UTC, lemeryfertitta commented on climbdex/templates/results.html.j2
> +                <button id="button-mirror" type="button" class="dropdown-item btn" data-bs-toggle="button" onclick="mirrorClimb()">
I think we should hide this when the board is not symmetrical (e.g. Kilter, Tension Spray). One idea would just be to query the DOM for `data-mirror-id` and hide the button when no results are found. There may be a better way as well.

I'm okay with the list item for now, but I could see a button being more desirable eventually. Probably better to save for a more complete UI redesign as more buttons/list items are added.

2024-09-06 21:17 UTC, ItsDang commented
Pulling whether layout is mirrored from db and using to show or hide Mirror Climb button. Updated Bluetooth to pass mirrored, will test on a TB2 at another gym when I can. Refactored whether the the Mirror Climb button is pressed or not.

2024-09-07 02:13 UTC, ItsDang commented
Realized I mixed up the mirrored sending to board over Bluetooth, was able to test on tb2 at another gym.

2024-09-07 03:48 UTC, ItsDang commented
Commited the change to light up  the right version, should be ready for review.

2024-09-07 21:19 UTC, lemeryfertitta requested changes

2024-09-07 21:19 UTC, lemeryfertitta commented on climbdex/db.py
> +            climbs.frames,
Seems like this line is a dupe of L107, but probably don't need to modify the search query at all for this changeset as described in other comment.

2024-09-07 21:19 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +  mirroredFrames,
Seems like mirroredFrames is unused and is just being overwritten later in the method.

2024-09-07 21:19 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +      mirroredFrames,
It seems like this is just `frames` from the SQL query results, not `mirroredFrames` - it also appears to be extra, given that frames are available above.

2024-09-07 21:19 UTC, lemeryfertitta commented on climbdex/static/js/results.js
> +    const mirroredBluetoothPacket = getBluetoothPacket(
Rather than calculate two separate packets and only use one, we can just do the following:

```javascript
const bluetoothPacket = getBluetoothPacket(
      isMirroredMode() ? mirroredFrames : frames,
      placementPositions,
      ledColors
    );
```

2024-09-08 01:32 UTC, ItsDang commented
Thanks for comments, it's cleaner. I've implemented and tested the mirrored button except for the Bluetooth on an actual board.

2024-09-08 15:19 UTC, lemeryfertitta approved these changes
Awesome, thanks for this very useful feature. I won't be near a board to test the bluetooth anytime soon, but the logic looks correct and we can always push another update if needed. Will get this merged and deployed now

2024-09-08 15:20 UTC, merged

2024-09-08 19:14 UTC, gardaholm commented
Nice and really needed addition! 
Will do some tests tomorrow

2024-09-09 02:39 UTC, ItsDang commented
@lemeryfertitta, Thanks for the help cleaning up the code! And thanks for testing @gardaholm.

2024-09-09 06:45 UTC, gardaholm commented
Didn't had any troubles with mirroring and lighting up the routes. Also behaves as I would expect it (similar to the app). If you mirror once, all upcoming routes show up as mirrored. Really nice!

Only issue I had is documented here https://github.com/lemeryfertitta/Climbdex/issues/45#issuecomment-2337255576, but thats part of the overall bluetoot discussion I guess