Set climbs
lemeryfertitta/Climbdex pull request #97
Opened 2024-09-11 05:44 UTC by ItsDang

For #47. Would like some feedback, I did try and set a draft boulder, didn't set a finalized boulder yet.
By default I have the boulder's set to draft and no matching, biased here, can swap and setter angle to None.

<img width="475" alt="Screen Shot 2024-09-11 at 1 38 15 AM" src="https://github.com/user-attachments/assets/0e42fb07-3da8-4796-9a72-2c1fa8cb5f8c">
<img width="498" alt="Screen Shot 2024-09-11 at 1 38 27 AM" src="https://github.com/user-attachments/assets/e5e7eb7e-7d76-4b1c-8ec1-4b7c75baa2b4">

I added the no matching button so users don't have to type it out in the description. It prepends it to the description if it exists.

At some point after this PR would like to include drafts in search results so that you publish/edit drafts if you are logged in.

2024-09-11 19:46 UTC, lemeryfertitta requested changes
A few very minor changes requested but generally LGTM, thanks!

I tested this briefly and everything worked great.

2024-09-11 19:46 UTC, lemeryfertitta commented on climbdex/api.py
> +@blueprint.route("/api/v2/climbs", methods=["POST"])
```suggestion
@blueprint.route("/api/v1/climbs", methods=["POST"])
```

Should be v1, a v2 would be if we made breaking changes to a v1 version of the endpoint

2024-09-11 19:46 UTC, lemeryfertitta commented on climbdex/api.py
> +        frames_pace=0
I think it's fine to include these in the initial API as non-required fields. They are used for setting routes, which is something that eventually would be nice to support

2024-09-11 19:46 UTC, lemeryfertitta commented on climbdex/templates/climbCreation.html.j2
> +                Boulder saved successfully!
```suggestion
                Boulder published successfully!
```

2024-09-11 19:46 UTC, lemeryfertitta commented on climbdex/templates/climbCreation.html.j2
> +                <h5 class="modal-title">Set a boulder:</h5>
```suggestion
                <h5 class="modal-title">Publish a boulder:</h5>
```

2024-09-11 19:46 UTC, lemeryfertitta commented on climbdex/templates/climbCreation.html.j2
> +                        +
```suggestion
                        Publish
```

I think calling this "publish" helps to make it clear that this is being submitted to a database somewhere.

2024-09-11 19:46 UTC, lemeryfertitta commented on climbdex/templates/climbCreation.html.j2
> +        <script>
Wasn't strict on this elsewhere, but I do think its a bit cleaner to have the script content moved to `climbCreation.js` so that all of the JS is in one place. Kind of hard to figure out where everything is when it's in a mix of HTML tags and script files.

2024-09-12 03:26 UTC, ItsDang commented on climbdex/api.py
> +@blueprint.route("/api/v2/climbs", methods=["POST"])
I guess my assumption was that it would be the same version as the boardlib api? But it's different so I kinda get it.

2024-09-12 17:31 UTC, lemeryfertitta commented on climbdex/api.py
> +@blueprint.route("/api/v2/climbs", methods=["POST"])
Ah I see - that API is actually the Aurora API. Maybe it would have been better to do a complete copy of the Aurora API but we're pretty far from that currently, so I'm thinking of the Climbdex API as something totally separate that sometimes corresponds to similar Aurora API calls.

2024-09-12 17:35 UTC, lemeryfertitta approved these changes

2024-09-12 17:35 UTC, merged